# Sử dụng image Node.js 20
FROM node:20-alpine

# Thiết lập thư mục làm việc
WORKDIR /app

# Sao chép package.json và package-lock.json từ thư mục app
COPY app/package*.json ./

# Cài đặt dependencies
RUN npm install

# Sao chép mã nguồn từ thư mục app
COPY app/ .

# Expose cổng 3001
EXPOSE 3001

# Chạy ứng dụng
CMD ["npm", "run", "dev"]