version: '3.8'

services:
  app:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/src/database:/app/src/database
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/auth/me"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
  database:

